#!/bin/bash
# La CI deve girare sullo stesso Python della produzione.
#
# Esiste perché il 13-08-2026 Dependabot ha proposto il salto del runtime del
# status-api da 3.12 a 3.14 (PR #46) e la CI era verde: i test giravano su 3.12
# pinnato a mano in quattro punti dei workflow, mentre l'immagine ne dichiarava
# un altro. Verde significava soltanto che le wheel hash-locked si installavano
# su 3.14 — nessun test ha mai eseguito su quell'interprete.
#
# Il numero resta scritto in otto posti perché setup-python non legge un
# Dockerfile e il Dockerfile non legge un file di versione: la duplicazione non
# si elimina, si sorveglia. Stessa scelta di scripts/check-image-users.sh.
#
# Il sesto posto — `sonar.python.version` — è stato aggiunto qui il 13-08-2026
# dopo averlo trovato fermo a 3.12 mentre produzione e CI erano già su 3.14: la
# prima versione di questo script sorvegliava cinque posti su sei, e il posto
# scoperto è proprio quello che è andato alla deriva. Un gate che copre quasi
# tutto lascia la deriva esattamente dove non guarda.
set -euo pipefail

dockerfile="services/public-status-api/Dockerfile"

# `FROM python:3.14.0-slim` -> `3.14`. L'immagine pinna la patch, la CI il minor:
# confrontiamo il minor, l'unico livello che entrambi dichiarano.
riga_from=$(grep -m1 -E '^FROM python:' "$dockerfile" || true)
if [ -z "$riga_from" ]; then
  echo "FAIL: ${dockerfile} non dichiara nessun 'FROM python:'" >&2
  exit 1
fi
atteso=$(sed -E 's/^FROM python:([0-9]+\.[0-9]+).*/\1/' <<<"$riga_from")

if ! grep -qE '^[0-9]+\.[0-9]+$' <<<"$atteso"; then
  echo "FAIL: versione non riconosciuta in ${dockerfile}: ${riga_from}" >&2
  exit 1
fi

fallimenti=0
trovati=0

while IFS= read -r riga; do
  trovati=$((trovati + 1))
  file=${riga%%:*}
  resto=${riga#*:}
  numero_riga=${resto%%:*}
  # `          python-version: "3.14"` -> `3.14`
  versione=$(sed -E 's/.*python-version:[[:space:]]*"?([^"[:space:]]+)"?.*/\1/' <<<"$riga")

  if [ "$versione" = "$atteso" ]; then
    echo "ok: ${file}:${numero_riga} -> ${versione}"
  else
    echo "FAIL: ${file}:${numero_riga} usa Python ${versione}, l'immagine ${atteso}" >&2
    fallimenti=1
  fi
done < <(grep -rn 'python-version:' .github/workflows/ | sort)

# Zero occorrenze non è un successo: vorrebbe dire che i workflow hanno smesso
# di pinnare la versione e girano su quella di default del runner, che cambia
# sotto di noi senza che nessun diff lo mostri.
if [ "$trovati" -eq 0 ]; then
  echo "FAIL: nessun 'python-version:' nei workflow — la CI gira sul default del runner" >&2
  exit 1
fi

# Sesto posto, con una sintassi tutta sua: `sonar.python.version=3.14`, non
# `python-version:`, quindi il ciclo qui sopra non lo vedrebbe mai. Sbagliarlo
# non rompe nessun test — SonarCloud analizza e basta, con le regole tarate
# sull'interprete sbagliato. È il tipo di deriva che resta verde per sempre.
# Settimo posto, scoperto da un audit il 19-08-2026: l'INTESTAZIONE dei due lockfile.
# `pip-compile` risolve i marker d'ambiente contro l'interprete che lo esegue, quindi
# un lock compilato su 3.12 e installato su 3.14 e' la chiusura di un interprete che
# non e' quello che gira. Non rompe nulla di rumoroso — `--require-hashes` rifiuta
# solo cio' che non e' elencato — ma indebolisce "hash-locked" da "questo e' cio' che
# la produzione installa" a "questo e' cio' che una risoluzione su 3.12 avrebbe
# installato". Sorvegliarlo costa tre righe; accorgersene costa un audit.
for lock in services/public-status-api/requirements.txt services/public-status-api/requirements-dev.txt; do
  riga_lock=$(grep -m1 -E '^# This file is autogenerated by pip-compile with Python' "$lock" || true)
  if [ -z "$riga_lock" ]; then
    echo "FAIL: ${lock} non dichiara con quale Python e' stato compilato" >&2
    fallimenti=1
    continue
  fi
  versione_lock=${riga_lock##* }
  if [ "$versione_lock" = "$atteso" ]; then
    echo "ok: ${lock} -> ${versione_lock}"
  else
    echo "FAIL: ${lock} e' stato compilato con Python ${versione_lock}, l'immagine usa ${atteso}." >&2
    echo "      Rigenera con python${atteso} -m piptools compile --generate-hashes ..." >&2
    fallimenti=1
  fi
done

file_sonar="sonar-project.properties"
riga_sonar=$(grep -m1 -E '^sonar\.python\.version=' "$file_sonar" || true)
if [ -z "$riga_sonar" ]; then
  echo "FAIL: ${file_sonar} non dichiara nessun 'sonar.python.version'" >&2
  exit 1
fi
versione_sonar=${riga_sonar#*=}

if [ "$versione_sonar" = "$atteso" ]; then
  echo "ok: ${file_sonar} -> ${versione_sonar}"
else
  echo "FAIL: ${file_sonar} dichiara Python ${versione_sonar}, l'immagine ${atteso}" >&2
  fallimenti=1
fi

if [ "$fallimenti" -ne 0 ]; then
  echo "" >&2
  echo "La CI proverebbe un interprete che la produzione non ha. Allinea i" >&2
  echo "workflow, i lockfile e sonar-project.properties al Dockerfile (o" >&2
  echo "viceversa) nello stesso commit." >&2
  exit 1
fi

echo "i ${trovati} pin dei workflow, i due lockfile e ${file_sonar} sono su Python ${atteso}, come l'immagine"
